#ifndef RKEM_PARAMS_H
#define RKEM_PARAMS_H

#define RKEM_K 5
#define RKEM_N 128
#define RKEM_Q 7681 // 2^9 * 15 + 1
#define RKEM_ETA1 2
#define RKEM_ETA2 2
#define RKEM_ETA3 192
#define RKEM_SYMBYTES 32
#define RKEM_MSGBYTES 16
#define RKEM_POLYBYTES 208
#define RKEM_POLYVECBYTES (RKEM_K * RKEM_POLYBYTES)
#define RKEM_POLYCOMPRESSEDBYTES 48
#define RKEM_POLYVECCOMPRESSEDBYTES (RKEM_K * 160)
#define RKEM_PUBLICKEYBYTES RKEM_POLYVECBYTES
#define RKEM_SECRETKEYBYTES (2 * RKEM_POLYVECBYTES)
#define RKEM_CIPHERTEXTBYTES (RKEM_POLYVECCOMPRESSEDBYTES + RKEM_POLYCOMPRESSEDBYTES)

#endif
