#ifndef RKEM_PARAMS_H
#define RKEM_PARAMS_H

#define RKEM_K 5
#define RKEM_N 128
#define RKEM_Q 7681
#define RKEM_ETA1 2
#define RKEM_ETA2 2
#define RKEM_ETA3 192
#define RKEM_LEN_SEED 32
#define RKEM_LEN_MSG 16
#define RKEM_LEN_POLY 208
#define RKEM_LEN_POLYVEC (RKEM_K * RKEM_LEN_POLY)
#define RKEM_LEN_POLY_COMPRESSED 48
#define RKEM_LEN_POLYVEC_COMPRESSED (RKEM_K * 160)

#endif
