#ifndef KYBER_PARAMS_H
#define KYBER_PARAMS_H

#define KYBER_K 3
#define KYBER_N 256
#define KYBER_Q 3329
#define KYBER_LEN_SEED 32
#define KYBER_LEN_SHARED_SECRET 32
#define KYBER_LEN_POLY 384
#define KYBER_LEN_POLYVEC (KYBER_K * KYBER_LEN_POLY)
#define KYBER_ETA1 2
#define KYBER_LEN_POLY_COMPRESSED 128
#define KYBER_LEN_POLYVEC_COMPRESSED (KYBER_K * 320)
#define KYBER_ETA2 2
#define KYBER_INDCPA_LEN_MSG (KYBER_LEN_SHARED_SECRET)
#define KYBER_INDCPA_LEN_PUBLIC_KEY (KYBER_LEN_POLYVEC + KYBER_LEN_SEED)
#define KYBER_INDCPA_LEN_SECRET_KEY (KYBER_LEN_POLYVEC)
#define KYBER_INDCPA_LEN_CIPHERTEXT (KYBER_LEN_POLYVEC_COMPRESSED + KYBER_LEN_POLY_COMPRESSED)
#define KYBER_LEN_PUBLIC_KEY (KYBER_INDCPA_LEN_PUBLIC_KEY)
#define KYBER_LEN_SECRET_KEY (KYBER_INDCPA_LEN_SECRET_KEY + KYBER_INDCPA_LEN_PUBLIC_KEY + 2 * KYBER_LEN_SEED)
#define KYBER_LEN_CIPHERTEXT (KYBER_INDCPA_LEN_CIPHERTEXT)

#endif
